param(
    [string]$SourceRoot = "$env:APPDATA\Code\User\prompts",
    [string]$DestinationRoot = "$PSScriptRoot\..\copilot-skills",
    [string[]]$SkillNames,
    [switch]$CleanDestination
)

$ErrorActionPreference = "Stop"

function Write-Info {
    param([string]$Message)
    Write-Host "[sync-copilot-skills] $Message"
}

if (-not (Test-Path -LiteralPath $SourceRoot)) {
    throw "Source root not found: $SourceRoot"
}

$resolvedDestination = (Resolve-Path -LiteralPath (Split-Path -Parent $DestinationRoot) -ErrorAction SilentlyContinue)
if (-not $resolvedDestination) {
    $parent = Split-Path -Parent $DestinationRoot
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
}

New-Item -ItemType Directory -Path $DestinationRoot -Force | Out-Null

if ($CleanDestination) {
    Write-Info "Cleaning destination: $DestinationRoot"
    Get-ChildItem -LiteralPath $DestinationRoot -Force | Remove-Item -Recurse -Force
}

$allSkillDirs = Get-ChildItem -LiteralPath $SourceRoot -Directory
if ($SkillNames -and $SkillNames.Count -gt 0) {
    $selected = $allSkillDirs | Where-Object { $SkillNames -contains $_.Name }
    $missing = $SkillNames | Where-Object { $_ -notin $selected.Name }
    if ($missing.Count -gt 0) {
        Write-Warning ("Requested skills not found: " + ($missing -join ", "))
    }
}
else {
    $selected = $allSkillDirs
}

$copied = @()
foreach ($dir in $selected) {
    $skillFile = Join-Path $dir.FullName "SKILL.md"
    if (-not (Test-Path -LiteralPath $skillFile)) {
        continue
    }

    $target = Join-Path $DestinationRoot $dir.Name
    if (Test-Path -LiteralPath $target) {
        Remove-Item -LiteralPath $target -Recurse -Force
    }

    Copy-Item -LiteralPath $dir.FullName -Destination $target -Recurse -Force
    $copied += [PSCustomObject]@{
        Skill = $dir.Name
        Source = $dir.FullName
        Target = $target
    }
    Write-Info "Synced $($dir.Name)"
}

$manifestPath = Join-Path $DestinationRoot "_manifest.md"
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"

$manifestLines = @(
    "# Copilot Skill Manifest",
    "",
    "Generated by .github/scripts/sync-copilot-skills.ps1",
    "",
    "- Synced at: $timestamp",
    "- Source root: $SourceRoot",
    "- Destination root: $DestinationRoot",
    "- Skill count: $($copied.Count)",
    "",
    "| Skill | Local Path |",
    "|---|---|"
)

foreach ($row in ($copied | Sort-Object Skill)) {
    $localPath = ".github/copilot-skills/$($row.Skill)/SKILL.md"
    $manifestLines += "| $($row.Skill) | $localPath |"
}

Set-Content -LiteralPath $manifestPath -Value $manifestLines -Encoding UTF8

Write-Info "Wrote manifest: $manifestPath"
Write-Info "Done. Synced $($copied.Count) skill(s)."
